name: pkgcheck

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      # force all history to be pulled for git-related checks
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Configure pkgcheck cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pkgcheck
          ~/.cache/pkgcore
        key: pkgcheck # static value to force cache pull

    - name: Install pkgcheck
      run: |
        pip install --upgrade pip
        # pkgcore git required for repos.conf update -- drop on new release
        pip install "pkgcore @ https://github.com/pkgcore/pkgcore/archive/master.tar.gz#egg=pkgcore"
        pip install pkgcheck

    - name: Sync gentoo repo
      run: sudo env "PATH=$PATH" pmaint sync gentoo

    - name: Regen repo metadata
      run: sudo env "PATH=$PATH" pmaint regen --dir ~/.cache/pkgcheck/repos .

    - name: Run pkgcheck
      run: sudo env "PATH=$PATH" pkgcheck scan --exit
